name: Continuous Integration
run-name: Build ${{ github.ref }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
      - run: composer install
      - run: composer archive --format tar.gz --dir dist/ --file muziekpraktijkvivo
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: muziekpraktijkvivo
          path: dist/muziekpraktijkvivo.tar.gz
